### ISSUE TITLE
Søk med ÆØÅ feiler signaturvalidering på serveren

### ISSUE THREAD

**Issue by asjafjell** [digipost/digipost-api-client-java#36]
Server forventer følgende signert:

```
GET
/recipients/search/%c3%a5%c3%a5%c3%a5%c3%a6%c3%a6%c3%b8%c3%b8
date: Mon, 13 Mar 2017 11:17:08 GMT
x-digipost-userid: 1000
```
Klienten signerer følgende:
```
GET
/recipients/search/åååææøø
date: Mon, 13 Mar 2017 11:17:08 GMT
x-digipost-userid: 1000
```

Det er vel mest korrekt å fikse klienten siden request path inngår i request og den er jo URL-encodet.

**Comment by froden** [comment]
Fixed in v10.1 https://github.com/digipost/digipost-api-client-java/pull/61
