### ISSUE TITLE
Compatibility issues with Java 1.8.0 update 141 

### ISSUE THREAD

**Issue by terjemeg** [digipost/digipost-api-client-java#45]
The test below returns an empty inbox if executed with Java 1.8.0 update 141 (The same result using 1.8.0 update 144). No exceptions are thrown.

However, if using Java 1.8.0 update 92, inbox documents are returned as expected. 

Edit the static members according to your own Digipost account before running the test. 

```java
import no.digipost.api.client.DigipostClient;
import no.digipost.api.client.DigipostClientConfig;
import no.digipost.api.client.SenderId;
import no.digipost.api.client.representations.inbox.Inbox;
import no.digipost.api.client.representations.inbox.InboxDocument;
import no.digipost.api.client.security.FileKeystoreSigner;
import no.digipost.api.client.security.Signer;
import org.junit.Test;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

/**
*
*/
public class DigipostTest {

    private static final String URL = "https://api.digipost.no";
    private static final long ACCOUNT_ID = 1234567L;
    private static final String CERT_PATH = "/cert/certificate.p12";
    private static final String CERT_PW = "xxx";
    private static final SenderId SENDER_ID = new SenderId(ACCOUNT_ID);

    @Test
    public void testDigipost() {
        DigipostClient digipostClient = newClient();
        Inbox inbox = digipostClient.getInbox(SENDER_ID, 0, 100);
        for (InboxDocument inboxDocument : inbox.documents) {
            System.out.println(inboxDocument);
        }
    }

    private DigipostClient newClient() {
        DigipostClientConfig clientConfig = new DigipostClientConfig.DigipostClientConfigBuilder().build();
        return new DigipostClient.DigipostClientBuilder(URL,
                ACCOUNT_ID,
                createSigner(),
                clientConfig)
                .build();
    }

    private Signer createSigner() {
        try {
            InputStream certInputStream = getStream(CERT_PATH);
            return new FileKeystoreSigner(certInputStream, CERT_PW);
        } catch (Exception e) {
            throw new IllegalStateException("Could not initialize Digipost client", e);
        }
    }

    private static InputStream getStream(String path) throws FileNotFoundException {
       InputStream inputStream = DigipostTest.class.getResourceAsStream(path);
        if (inputStream == null) {
            File file = new File(path);
            return new FileInputStream(file);
        }
        return inputStream;
    }
}

```

**Comment by asjafjell** [comment]
Takk for godt eksempel!  Jeg svarer på norsk siden min opprinnelige kontakt med deg var på norsk.

Hvilken versjon av biblioteket er det du ønsker å bruke? Jeg antar det er versjon 8.0 for innboks-funksjonalitet?

**Comment by terjemeg** [comment]
Jeg har forsøkt med 8.4.1, 8.5 og 9.0 RC1. Ønsker i utgangspunktet å bruke siste release versjon, men kan bruke en eldre versjon dersom den fungerer med Java 1.8.0 update 141.

Jeg skal kun benytte api'et til å hente inbox'en og å slette inbox dokumenter.

**Comment by asjafjell** [comment]
Beklager, her er det jeg som surrer. Jeg så på versjonene for feil klient.  Vi skal ta en kikk på dette her nå.

**Comment by asjafjell** [comment]
Vi har nå testet noen tester mot API med noen tester vi selv har, og de flyr fint med versjon _1.8.0 update 144_. Jeg skal teste med din kode for å se hva vi finner ut.

**Comment by asjafjell** [comment]
Heisann!

Først vil jeg gi deg kudos enda en gang for utmerket eksempelkode som vi kunne teste med. Vi har nå kjørt med siste stabile versjon av klienten, _8.5_ og java _1.8.0 update 144_. Vi får fint hentet ut dokumenter, så her trenger vi mer informasjon fra deg. Er det slik at det å hente innboksen gir null dokumenter ut kun ved å endre Java-versjon, og at du ikke får noen feilmeldinger?

**Comment by terjemeg** [comment]
Ja, det stemmer. Jeg får et Inbox objekt i retur: Inbox{documents=[]}. Jeg tok testkoden med meg hjem og kjørte den på en annen PC med samme resultat. Installerte JDK 1.8.0 update 144 og la inn JCE 8. Har tidligere sett på Wireshark traces og det kommer mer "application data" med Java 1.8.0 update 92

**Comment by terjemeg** [comment]
Wireshark traces er like for JDK 1.8.0 update 144 og Java 1.8.0 update 92 med testkoden.  Det blir kun forskjell hvis koden henter document content.  Alt ser likt ut inntil man kommer til unmarshal:
```java
 JAXB.unmarshal(execute.getEntity().getContent(), entityType);
```

**Comment by terjemeg** [comment]
Mulig denne har med saken å gjøre:

https://stackoverflow.com/questions/40889384/jaxb-namespace-annotation-not-inherited-during-unmarshalling-regression-in-jd

**Comment by asjafjell** [comment]
Vi har nå klart å gjenskape problemet på vår side, kan det se ut som. Vi gjør testing nå for å finne ut av det.

**Comment by asjafjell** [comment]
Da kan vi informere om at vi har løst problemet. Det ser ut til at det er en bug i JAXB i nyere versjoner av java. Ved å sette disse eksplisitt selv til en eldre versjon så får vi det til å fungere:
```
<dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <scope>runtime</scope>
            <version>2.2.11</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <scope>runtime</scope>
            <version>2.2.11</version>
        </dependency>
```

**Comment by asjafjell** [comment]
Dette er nå fikset permanent i versjon [8.6](https://github.com/digipost/digipost-api-client-java/releases/tag/8.6). Jeg lukker denne for nå, og så får du bare skrike ut om det skulle oppstå flere problemer knyttet til dette. Takk for en god dialog og gode tips underveis.

**Comment by terjemeg** [comment]
Fint, jeg kan bekrefte at det fungerer på min side også.

**Comment by mikand13** [comment]
@asjafjell Vurdert å uppe jaxb til 4.0.2? Jeg må override for å være kompatibel med java 18/19. Ser ut til å funke knirkefritt her.
