### ISSUE TITLE
Checking for boolValue == Boolean.TRUE won't always yield the expected result

### ISSUE THREAD

**Issue by Valentin-Paramonov** [digipost/digipost-api-client-java#95]
https://github.com/digipost/digipost-api-client-java/blob/2c213dc62a1867672378a2f0fb4f0fbf0e7a623f/src/main/java/no/digipost/api/client/representations/Document.java#L122

Not all instances of `Boolean` in Java are the same object as `Boolean.TRUE`

To demonstrate:
```java
jshell> new Boolean(true) == true
$1 ==> true
jshell> new Boolean(true) == Boolean.TRUE
$2 ==> false
jshell> new Boolean("true") == true
$3 ==> true
jshell> new Boolean("true") == Boolean.TRUE
$4 ==> false
```
I know these two constructors are deprecated and their usage is rare, but nevertheless possible.

Please consider using 
```java
Boolean.TRUE.equals()
```
which is as safe, but works as expected:
```java
jshell> Boolean.TRUE.equals(new Boolean(true))
$6 ==> true
jshell> Boolean.TRUE.equals(new Boolean("true"))
$7 ==> true
jshell> Boolean.TRUE.equals(null)
$8 ==> false
```

**Comment by runeflobakk** [comment]
Good catch, and thanks for a well-explained issue! Would you be willing to submit a pull-request for the fix?

**Comment by Valentin-Paramonov** [comment]
Yes, sure. Not right away, but I'll do my best :slightly_smiling_face:
